### ISSUE TITLE
Issue with Arduino with SAMD21G18

### ISSUE THREAD

**Issue by kroa38** [NilsMinor/TMP117-Arduino#1]
Hello Nils
When i use the code on SAMD21G18 Arduino Board i have one bug when the upload is finish. The Bossa programmer freeze .
I have resolve this issue by moving the <Wire.begin()> call  on the TMP117::TMP117 class to the  TMP117::init .

Now it works on my both board AVR and SAMD21.

Thanks

**Comment by NilsMinor** [comment]
Hi kroa,

thanks for reporting I will check it this weekend. I think it is still better to call the wire.begin() method in  void setup() in order to use it also for other methods in the main Arduino script. If you call the begin() inside the TMP117 constructor you can only use the wire object inside the tmp117 class. But I might add a comment in or #ifdef in order to support also SAMD21.

- Nils
