### ISSUE TITLE
TMP117.cpp:290:1: error: control reaches end of non-void function [-Werror=return-type]

### ISSUE THREAD

**Issue by StefanL38** [NilsMinor/TMP117-Arduino#3]
I installed the library with the library-manager
the opened the example-code and tried to compile for an ESP32-Board

it reports an error:
TMP117.cpp:290:1: error: control reaches end of non-void function [-Werror=return-type]

So something seems to be wrong with the source-code.
Did you let compile your example-codes with reporting **ALL** errors enabled?

My personal Opinion: If you make a library avilable through the library-manager you should do at least some quality-checking. Otherwise you should upload your library just as a personal repository
best regards Stefan

**Comment by NilsMinor** [comment]
Hi @StefanL38,
thanks for reporting this issue. I think this issue was already fixed by a friendly guy who made a pull-request. I forgot to make the release in order to make it public available trough the Arduino library manager, sorry for that. I just made an other fix to the library in order to compile proper on other architectures then the one I used in the past. The fix is 1.0.2 and should be available in the next time.

My personal opinion: Yes you are right I should have checked the compile errors in stage "all" before publishing the library. Never changed this in my Arduino IDE so I didn't knew about this. However, Open Source software like my and all the other Arduino libraries are maintained by people creating this in their free time. In order to improve things it is always a good idea to report issues and create pull-request to submit changes. 

Best regards,
Nils
